### ISSUE TITLE
[Errno 2] No such file or directory: '/home/macagua/plonethemes.suite/src/nnsh.theme01/nnsh/theme01/template_overrides'

### ISSUE THREAD

**Issue by macagua** [mingtak/nnsh.theme01#1]
Hi 

When try to add this theme into my plone suite show the following error:
```
2015-08-16 10:34:48 WARNING Init Class collective.cover.tiles.edit.CustomTileEdit has a security declaration for nonexistent method 'publishTraverse'
Traceback (most recent call last):
  File "/home/macagua/plonethemes.suite/parts/instance/bin/interpreter", line 450, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/macagua/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/home/macagua/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/home/macagua/.buildout/eggs/z3c.jbot-0.7.1-py2.7.egg/z3c/jbot/metaconfigure.py", line 33, in handler
    factory(layer).registerDirectory(directory)
  File "/home/macagua/.buildout/eggs/z3c.jbot-0.7.1-py2.7.egg/z3c/jbot/manager.py", line 78, in registerDirectory
    for filename in os.listdir(directory):
zope.configuration.config.ConfigurationExecutionError: <type 'exceptions.OSError'>: [Errno 2] No such file or directory: '/home/macagua/plonethemes.suite/src/nnsh.theme01/nnsh/theme01/template_overrides'
  in:
  File "/home/macagua/plonethemes.suite/src/nnsh.theme01/nnsh/theme01/configure.zcml", line 24.2-27.8
    <browser:jbot
        directory="template_overrides"
        layer=".interfaces.ICustomTheme"
        />

(python2.7)macagua@dacagua:~/proyectos/plone/git/plonethemes.suite$
```

Temporally I fixed this error commenting the "browser:jbot" directive like this:

```
  <!--
  <browser:jbot
      directory="template_overrides"
      layer=".interfaces.ICustomTheme"
      />
      -->
```

**Comment by mingtak** [comment]
Thanks for fixed this issue
